### ISSUE TITLE
Block updates are not visible to the client until rejoin

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1178]
#### Issue description

I have a 25 block radius for spawn protection on my server, and an area plugin. However, players can now break blocks and get out of spawns, but it will only be visible to the player. There are no block breaking particles. Could it be some code change?
#### Steps to reproduce the issue

Go on a Genisys-run server, and use any area protection plugin or use the spawn protection setting, and switch to another account and try to break blocks at your spawn.
#### OS and versions

* Genisys: 1.2dev-c146443 "Ikaros"
* PHP: 7
* OS: Moto G (Android 5.1)

#### Crashdump, backtrace or other files
```
N/A
```

**Comment by dktapps** [comment]
I observed this issue myself. Try quitting the game and relogging in; does the broken block reappear?

**Comment by ChavoJoker** [comment]
I tried it and when i re-logged the blocks did reappear

**Comment by ABAxStorm** [comment]
@dktapps They do reappear but players can still get out of barriers.

**Comment by XxDXM-hippiexX** [comment]
The blocks just dont update..i also use iprotector. When you relog the 'broken blocks' do re appear.

**Comment by ZizzyZizzy** [comment]
This was fixed today (client updating blocks), but spawn protection doesn't work. Neither with the native spawn-protection setting, nor plugins like iProtector. Very bad.

**Comment by markkrueg** [comment]
@ZizzyZizzy 

> This was fixed today (client updating blocks)

How was this fixed today? I think the problem is that it has not yet been isolated/fixed.

**Comment by LCraftPE** [comment]
iProtector doesn't work ?  You going to correct this ?

**Comment by markkrueg** [comment]
I believe 1e804e4 fixes this. I have been testing today; and it seems good.

**Comment by dktapps** [comment]
Just waiting for merge.

**Comment by dktapps** [comment]
Resolved as of commit 193a5c9. Closing.

**Comment by Guillaume351** [comment]
Still not entirely fixed. I have a MicroBattles plugin (coded by me), it was working correctly on 0.14 : After 15 seconds, I make a glass wall disappear. But client still see it, and you have to tap on each block to make it disappear. Block update are not working anymore by using setBlock method :/
