### ISSUE TITLE
@dktapps' Win10 edition bug checklist

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1337]
My issue tracker for Windows 10 Edition bugfixes

**UPDATE**: Some of these issues apparently also affect Gear VR. I cannot test with Gear VR, so help testing will be much appreciated!

**UPDATE 13/07/2016**: Yes, this list keeps getting longer, it's a pain. For every bug I fix, another springs up in its place. I'm making progress though.

**UPDATE 21/07/2016**: I'm currently battling with a nasty segmentation fault, so the update has been delayed. Any help finding/fixing it will be much appreciated.

**UPDATE 28/07/2016**: Big progress and stability improvements this week. General spazziness is resolved.

## List of things left to do:
- [x] Re-implement anvils and enchanting tables. This will be a freakishly complicated job due to the inconsistencies between PE/Win10 and the bugs in both.

## Notes to self:
- There needs to be a universal way to handle PE and W10 both, since there's no real way to tell them apart.
- Ordering is critical, and if not, then retrying failed transactions.
- _Any_ transaction should be executable, not just those that have a real source/destination (Critical for W10 crafting and inventory transactions)
- Hotbar mapping _MUST NOT CHANGE AT ALL_ **unless this is directly requested by the client**. Win10 will not request changes to hotbar mapping - only PE will, which should fix some annoying bugs.
- There seems to be some serious bugs in Win10 concerning temporary inventories such as enchanting tables and anvils. Win10 doesn't send changes to these slots at all, but PE does. I don't think this is fixable without major hacks.
</details>

## References:
- Windows 10 doesn't tell the host what's in the crafting grid: https://bugs.mojang.com/browse/MCPE-16366
- Some sounds (including anvil sounds) missing: https://bugs.mojang.com/browse/MCPE-16347
- Win10 crashes in multiplayer when 2 people use the same enchanting table https://bugs.mojang.com/browse/MCPE-16477

**Comment by House-Kitty-Mew** [comment]
I get this error while trying to craft on GearVR version
Notice: Undefined offset: 0 in phar:///srv/genisys/genisys.phar/src/pocketmine/Player.php on line 3494

**Comment by dktapps** [comment]
Common problem to all platforms using the desktop crafting GUI. The `windows-10-beta` branch fixes it if you'd like to try it.

**Comment by Bananaunymous** [comment]
I can't craft in Windows 10 edition beta :/
Notice: Undefined offset: 0 in phar:///home/pi/Documents/MCPE/PocketMine-iTX.phar/src/pocketmine/Player.php on line 3339

**Comment by Bananaunymous** [comment]
Can you try to fix Crafting for Minecraft Windows 10 edition ? Please  :-)

**Comment by dktapps** [comment]
Shut up and read the list.

**Comment by Bananaunymous** [comment]
HHmmm sorry :/

**Comment by House-Kitty-Mew** [comment]
i will help test with my GearVR, how do i check out the new version on docker?

**Comment by dktapps** [comment]
@House-Kitty-Mew The latest Win10 build can be found at https://gitlab.com/itxtech/genisys/builds/2152751/artifacts/file/Genisys_1.2dev-b6b5cd2.phar
Use that URL when you use cURL

**Comment by House-Kitty-Mew** [comment]
I get this when I stop the server.
`[17:37:44] [Server thread/INFO]: Done (44.568s)! For help, type "help" or "?"
Genisys> stop
Genisys> [17:37:52] [Server thread/INFO]: [CONSOLE: Stopping the server]
[17:37:52] [Server thread/INFO]: Unloading level "world"
[17:37:52] [Server thread/INFO]: Unloading level "nether"
[17:37:53] [Server thread/CRITICAL]: Error: "Call to a member function wait() on null" (EXCEPTION) in "/src/raklib/server/ServerHandler" at line 69
[17:37:53] [Server thread/EMERGENCY]: Crashed while crashing, killing process
[17:37:53] [Server thread/INFO]: Stopping other threads
Server has stopped
`

**Comment by dktapps** [comment]
argh. #1382

**Comment by Bananaunymous** [comment]
Why make separate versions of Genisys (MCPE - Win10) ? You can not group all in a single release ?

**Comment by dktapps** [comment]
@Bananaunymous it's a separate _branch_, not a separate version. It hasn't been merged into master yet because it's not stable.

**Comment by House-Kitty-Mew** [comment]
could u show me how to download new updated .phar of genisys of the win10, i been all over this site and its links, cant find how to do it.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2281878/artifacts/file/Genisys_1.2dev-e3b5bda.phar is the latest tested build

**Comment by dktapps** [comment]
New build: https://gitlab.com/itxtech/genisys/builds/2351736/artifacts/file/Genisys_1.2dev-5b74632.phar
This build fixes a bunch of things, the hotbar being one of them.

**Comment by dktapps** [comment]
New build: https://gitlab.com/itxtech/genisys/builds/2367231/artifacts/file/Genisys_1.2dev-8f5123f.phar
Fixes spam-inventory transactions and left-click-dragging items across inventory slots. (I wasn't expecting that last to suddenly start working)

**Comment by dktapps** [comment]
New build: https://gitlab.com/itxtech/genisys/builds/2378604/artifacts/file/Genisys_1.2dev-2f4c8db.phar
This fixes hotbar slot mapping universally, sending held items correctly and some item selection bugs.

**Comment by mote166** [comment]
Deprecated: Hotbar linkage should never be changed unless requested by the client in phar:///jar/versions/Genisys/Genisys_1.2dev-2f4c8db.phar/src/pocketmine/inventory/PlayerInventory.php on line 73 

.. fix ?

**Comment by House-Kitty-Mew** [comment]
@dktapps just want to thank u for posting the new builds, it makes it much quicker for me to implement updates

**Comment by dktapps** [comment]
@mote166 that's a plugin's fault. Plugins which work with the inventory will need to be updated when I release this update. setHotbarSlotIndex has been deprecated.

**Comment by House-Kitty-Mew** [comment]
i have gear VR, if u want tell me how to enable logging and exactly what to do to test something for u, then i will send u a copy of my logs :)

**Comment by dktapps** [comment]
@House-Kitty-Mew If you set `debug.level` to `2` in pocketmine.yml, that will output debug messages. But if something crashes you'll know about it regardless.

The main issue at the moment is a nasty segmentation fault that I can't seem to trace.

**Comment by House-Kitty-Mew** [comment]
"segmentation fault" Mind explaining a little further on this one? I too am a programmer so I would like to help as much as I can.

**Comment by dktapps** [comment]
@House-Kitty-Mew there's not much to it. Basically something attempts to read something it doesn't have access to and crashes. I have a suspicion what's causing it but it needs to be investigated, as it might even be a PHP issue.

**Comment by House-Kitty-Mew** [comment]
when used in docker it should have full permission, are u using sqlite?

**Comment by dktapps** [comment]
@House-Kitty-Mew it's not a permissions error as such. https://www.google.co.uk/search?q=segmentation+fault&oq=segmentation+fault&aqs=chrome..69i57j69i61l3.3173j0j7&sourceid=chrome&ie=UTF-8

**Comment by House-Kitty-Mew** [comment]
ah a memory problem, that could be tricky, maybe set all files permission as their needed? i know that could eat cpu but it would solve it, unless the ram might just be bad.

**Comment by EpicSteve33** [comment]
Game crashes if a Windows 10 player opens a chest, I was gonna open a new issue but I saw this check list so ya

**Comment by dktapps** [comment]
Big update: Fixes general inventory spazziness and strange behaviour, along with some improvements to hotbar behaviour on PE.
https://gitlab.com/itxtech/genisys/builds/2680153/artifacts/file/Genisys_unsupported-63769e6_2016-07-28_12-26-24.phar

**Comment by dktapps** [comment]
Please note that since recent updates, non-master builds will automatically crash themselves unless you set `settings.enable-testing` to `true` in your pocketmine.yml.

**Comment by dktapps** [comment]
I also recommend that you delete any Windows 10 players' dat files from players/ to get the best results where the hotbar is concerned.

**Comment by PeratX** [comment]
Nice job!

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2703075/artifacts/file/Genisys_unsupported-57a343a_2016-07-29_10-10-45.phar
Fixes furnace issues and support for 0.15.4

**Comment by TheAppleGamer** [comment]
Enchant tables need redone as well

**Comment by dktapps** [comment]
Yes, I am aware. There are unfortunately rather large holes in the protocol that I'm having difficulty working around.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2721731/artifacts/file/Genisys_unsupported-2489185_2016-07-30_10-12-31.phar
Completely fixed left-click-drag issues.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2743769/artifacts/file/Genisys_unsupported-99ba0ea_2016-07-31_04-45-47.phar
Added an option to disable verified transaction processing (currently required for anvils to work on Win10), fixed some duplication and creative mode issues.

**Comment by House-Kitty-Mew** [comment]
Just want to thank you again for always posting builds here, it always helps me out.

**Comment by badvision** [comment]
I ran into an odd issue in both the Android version and the GearVR version which I'll try to explain:
- Player pick slots are empty
- Try to pick up something from a chest and it doesn't stay and the slot goes empty again
- Add something to the active pick slot from player inventory and it stays
- I can then pull things out of a chest or from the creative menu in that slot but other empty slots don't work
- Add another item to the second slot from player inventory
- Take something from a chest or creative menu and it will go in that slot AND the first slot

Also another oddity:
- Place player inventory items in chest and they go in chest properly
- When closing chest, player also drops the same items on the ground as well

This is a bit screwy but it is consistent among both of the 0.15.4 clients (Android GearVR and Android)  I hope my description of the issue is helpful.

**Comment by dktapps** [comment]
@badvision are you sure you're up-to-date? I fixed these issues a few days ago

**Comment by dktapps** [comment]
The only issues I'm currently aware of are problems with anvils and enchantment tables. (That and an annoying segmentation fault).

**Comment by CLiu13** [comment]
Duplication still occurs with anvils when renaming items, and there seems to be duplication glitches with enchanting tables possibly as well (duplicate lapis).

Still investigating the segmentation fault.

**Comment by dktapps** [comment]
As I said in the commits, Win10 and PE both are far too buggy for this to work correctly. I'm having to hack a lot of things to work around various bugs with both of them.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2841633/artifacts/file/Genisys_unsupported-9ab6de8_2016-08-04_10-46-10.phar
This build fixes hotbar phantom items, held item bugs and some weird inventory size issues on PE.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2852122/artifacts/file/Genisys_unsupported-2c7c386_2016-08-04_04-40-12.phar
This build fixes issues with dropped items not being picked up to the last 9 inventory slots.

(An old hack caused this problem (from April). The moral of the story - hacks to fix client bugs should not affect functionality.)

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2879914/artifacts/file/Genisys_unsupported-5748d1f_2016-08-05_06-58-04.phar
Fixes an annoying dropped item pickup bug.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2892016/artifacts/file/Genisys_unsupported-e624d21_2016-08-06_06-13-26.phar
Fixed issues with chest viewing and content rearranging when pairing.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2913754/artifacts/file/Genisys_unsupported-313d9de_2016-08-08_12-31-37.phar
Restored PE anvil functionality (rename only), fixed anvils immediately closing when used, enchanting table fixes for PE. Hacks incoming to work around Win10 bugs.

**Comment by dktapps** [comment]
https://gitlab.com/itxtech/genisys/builds/2913848/artifacts/file/Genisys_unsupported-5ece53e_2016-08-08_12-39-13.phar
Removed spammy var_dump (sorry if anyone already used the above build)

**Comment by dktapps** [comment]
Okay guys, would you like to head over to #1621 ?
