### ISSUE TITLE
Segmentation fault at Startup

### ISSUE THREAD

**Issue by markkrueg** [iTXTech/Genisys#185]
Running PHP7 built from PeratX script and Genisys Build #36
Startup fails with a segmentation fault. I then try again, and again, and then it will finally run (sometimes up to 10 tries required). Once running it will run for hours without problems with many users playing.

I have a very large and complex world (7.2GB). This world was created and built in PocketMine-MP (no imports).

Is there any additional debug information I can get to help trace the source of this problem? It says (core dumped). Does this mean there is a core dump file somewhere?

Here is what it looks like when it fails:
```
[18:11:30] [Server thread/INFO]: 

		   PocketMine-iTX Genisys is a fork of PocketMine-MP.
		   Powered by iTX Technologies LLC.
		   Version: 1.0dev-36
		   Client Version: 0.13.1 alpha
		   You could get the lastest code on https://github.com/iTXTech/Genisys
		   Donate link: http://pl.zxda.net/plugins/203.html
		   如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
		

[18:11:30] [Server thread/INFO]: Loading pocketmine.yml...
[18:11:30] [Server thread/INFO]: Loading genisys.yml...
[18:11:30] [Server thread/INFO]: Loading server properties...
[18:11:30] [Server thread/INFO]: Selected English (eng) as the base language
[18:11:30] [Server thread/INFO]: Starting Minecraft: PE server version v0.13.1 alpha
[18:11:30] [Server thread/INFO]: Starting remote control listener
[18:11:30] [Server thread/INFO]: RCON running on 0.0.0.0:19135
[18:11:30] [Server thread/INFO]: Opening server on 0.0.0.0:19135
[18:11:30] [Server thread/DEBUG]: Server unique id: 78c480e4-c59d-30d8-8c94-abb793376748
[18:11:30] [Server thread/DEBUG]: Machine unique id: 1aaf81de-5e40-3011-8f88-04e776e0c049
[18:11:30] [Server thread/INFO]: This server is running Genisys version 1.0dev-36 "Amazing PHP7 !" (API 2.0.0)
[18:11:30] [Server thread/INFO]: Genisys is distributed under the LGPL License
[18:11:31] [Server thread/INFO]: Preparing level "Fantasy"
[18:11:31] [Server thread/INFO]: Preparing level "nether"
Segmentation fault (core dumped)
```
but if I try about 10 times I get a normally running server
```
[18:12:50] [Server thread/INFO]: 

		   PocketMine-iTX Genisys is a fork of PocketMine-MP.
		   Powered by iTX Technologies LLC.
		   Version: 1.0dev-36
		   Client Version: 0.13.1 alpha
		   You could get the lastest code on https://github.com/iTXTech/Genisys
		   Donate link: http://pl.zxda.net/plugins/203.html
		   如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
		

[18:12:50] [Server thread/INFO]: Loading pocketmine.yml...
[18:12:50] [Server thread/INFO]: Loading genisys.yml...
[18:12:50] [Server thread/INFO]: Loading server properties...
[18:12:50] [Server thread/INFO]: Selected English (eng) as the base language
[18:12:50] [Server thread/INFO]: Starting Minecraft: PE server version v0.13.1 alpha
[18:12:50] [Server thread/INFO]: Starting remote control listener
[18:12:50] [Server thread/INFO]: RCON running on 0.0.0.0:19135
[18:12:50] [Server thread/INFO]: Opening server on 0.0.0.0:19135
[18:12:50] [Server thread/DEBUG]: Server unique id: 78c480e4-c59d-30d8-8c94-abb793376748
[18:12:50] [Server thread/DEBUG]: Machine unique id: 1aaf81de-5e40-3011-8f88-04e776e0c049
[18:12:50] [Server thread/INFO]: This server is running Genisys version 1.0dev-36 "Amazing PHP7 !" (API 2.0.0)
[18:12:50] [Server thread/INFO]: Genisys is distributed under the LGPL License
[18:12:50] [Server thread/INFO]: Preparing level "Fantasy"
[18:12:50] [Server thread/INFO]: Preparing level "nether"
[18:12:50] [Server thread/INFO]: Starting GS4 status listener
[18:12:50] [Server thread/INFO]: Setting query port to 19135
[18:12:50] [Server thread/INFO]: Query running on 0.0.0.0:19135
[18:12:50] [Server thread/INFO]: Default game type: Survival Mode
[18:12:50] [Server thread/INFO]: Done (0.574s)! For help, type "help" or "?"
```
Also, at some point during one of the 10 tries it may or may not replace my server.properties file with the default one at the point it segfaults! So I now have a backup server.properties that I always copy just before each startup attempt. My server.properties file (rcon password changed).
```
#Properties Config file
#Thu Jan 28 18:13:02 UTC 2016
motd=§5Test §6Server
server-port=19135
white-list=off
announce-player-achievements=on
spawn-protection=150
max-players=100
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=Fantasy
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=on
rcon.password=xxxxxxxx
auto-save=on
```
Could this have anything to do with the "GS4 status listener" and the fact that I am running port 19135?

I am running Ubuntu Server 14.04.3 LTS with the following PHP7 build:
```
bash ./compile.sh -t linux64 -j 2 -c -f x86_64
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependecies
[opt] Set target to linux64
[opt] Set make threads to 2
[opt] Will force compile cURL
[opt] Enabling abusive optimizations...
[INFO] Compiling for Linux x86_64
[PHP] downloading 7.0.2... done!
[zlib] downloading 1.2.8... checking... compiling... installing... cleaning... done!
[mcrypt] downloading 2.5.8... checking... compiling... installing... cleaning... done!
[GMP] downloading 6.1.0... checking... compiling... installing... cleaning... done!
[mbed TLS] downloading 2.2.0... checking... compiling... installing... cleaning... done!
[cURL] downloading curl-7_46_0... checking... compiling... installing... cleaning... done!
[YAML] downloading 0.1.6... checking... compiling... installing... cleaning... done!
[libpng] downloading 1.6.20... checking... compiling... installing... cleaning... done!
[PHP pthreads] downloading 3.1.5... done!
[PHP Weakref] downloading 0.3.2... done!
[PHP YAML] downloading 2.0.0RC6... done!
[PHP] enabling optimizations... checking... compiling... installing... generating php.ini... done!
[INFO] Cleaning up... done!
[PocketMine] You should start the server now using "./start.sh."
[PocketMine] If it doesn't work, please send the "install.log" file to the Bug Tracker.
```

**Comment by darkspive** [comment]
I also could not

**Comment by SleepSpace9** [comment]
I got the same problem with my self compiled php7, but the process exits without "Segmentation fault".
My OS is the same like **markkrueg** (Ubuntu Server 14.04.3 LTS) and I compiled php7 the same way/parameters.
Nothing more to see with higher debug level. Sometimes the server runs and i can do commands like "list", but when I start the mcpe client and open the server list the server immediately stops without any further console output.

**Comment by BlindTail** [comment]
I have the same problem as @markkrueg 

My server runs fine once it gets started (after 5 to 10 reboots; I had to set up a loop). It can go for an hour with over 30 users and quite a few plugins; no problem. I automatically reboot every hour just out of habit.

But every time I start it up I get bunch of failed startups with "Segmentation fault (core dumped)" before it finally takes. I am running from current github source and on Ubuntu Server 14.04.3 LTS.

I also used PeratX script; so my PHP versions are same as @markkrueg

**Comment by PeratX** [comment]
Try the latest php 7.0.3

**Comment by markkrueg** [comment]
@PeratX Same problem with 7.0.3.
```
bash compile.sh -t linux64 -j 2 -c -f x86_64
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependecies
[opt] Set target to linux64
[opt] Set make threads to 2
[opt] Will force compile cURL
[opt] Enabling abusive optimizations...
[INFO] Compiling for Linux x86_64
[PHP] downloading 7.0.3... done!
[zlib] downloading 1.2.8... checking... compiling... installing... cleaning... done!
[mcrypt] downloading 2.5.8... checking... compiling... installing... cleaning... done!
[GMP] downloading 6.1.0... checking... compiling... installing... cleaning... done!
[mbed TLS] downloading 2.2.0... checking... compiling... installing... cleaning... done!
[cURL] downloading curl-7_46_0... checking... compiling... installing... cleaning... done!
[YAML] downloading 0.1.6... checking... compiling... installing... cleaning... done!
[libpng] downloading 1.6.20... checking... compiling... installing... cleaning... done!
[PHP pthreads] downloading 3.1.5... done!
[PHP Weakref] downloading 0.3.2... done!
[PHP YAML] downloading 2.0.0RC6... done!
[PHP] enabling optimizations... checking... compiling... installing... generating php.ini... done!
[INFO] Cleaning up... done!
[PocketMine] You should start the server now using "./start.sh."
[PocketMine] If it doesn't work, please send the "install.log" file to the Bug Tracker.
```

I still have to run start.sh up to 10 times before the server will continue to run. I am using port 19135. It is very stable once it gets running.

Any chance we can re-open this issue?

**Comment by gaoyichuan** [comment]
Reopening

**Comment by markkrueg** [comment]
Any ideas how we could further troubleshoot this? The problem continues with updated versions of PHP7 as well as newer builds of Genisys.

**Comment by PeratX** [comment]
@markkrueg Try to delete temp files created by php

**Comment by markkrueg** [comment]
There were quite a few php* files in /tmp. I deleted them. Still the first several boot attempts got me

Segmentation fault (core dumped)

**Comment by Driesboy** [comment]
Fixed?

**Comment by markkrueg** [comment]
Driesboy said:
> Fixed?

I just did a build based on current github source. The first time I started the server it segfaulted. The second time it did not. So the bug still seems to be there.

Is there a particular code change which you believe fixed this bug? Or should have?

**Comment by Driesboy** [comment]
i dont have this on windows

**Comment by markkrueg** [comment]
I believe it only occurs on Linux.

**Comment by markkrueg** [comment]
This is definitely still happening with current github version. As far as I can tell it was never fixed.

Is there a code change that you thought fixed this? Maybe I can test further?

**Comment by jonathankerans** [comment]
I am having the same exact issue. If anybody has any ideas, please propose them. It will be greatly appreciated!

**Comment by jonathankerans** [comment]
@markkrueg Just to let you know, this issue forum is still closed and you might want to open it back up if you still need a resolution.

**Comment by ishitatsuyuki** [comment]
This is upstream issue. pthreads sucks. We have no way to switch to an alternative easily.
