### ISSUE TITLE
Console not taking commands

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#381]
After the server has been running for a while the console stops taking commands.
If I enter a command in the console nothing happens until I restart the server then it happens again.

**Comment by PeratX** [comment]
Yes and I think it is related to pthreads

**Comment by astersx** [comment]
Search in genisys.yml  
and put checkmovement:true

**Comment by NML32** [comment]
That's what it's set to.

**Comment by thebigsmileXD** [comment]
Fixed in ClearSky, maybe you have a look. This really is a critical bug.

**Comment by NML32** [comment]
I'm using the latest build #79 and I'm unable to type commands in the console. Seems the issues is back.

**Comment by NML32** [comment]
I'm running the server on Windows 10 and with the latest build the bug is back where I can't enter commands from the console. Please re-open the ticket and find a fix.
